### ISSUE TITLE
paplay method

### ISSUE THREAD

**Issue by nikhilbv** [hg8/battery-full-notification#2]
Does the paplay command really works?
Can you change the notification tone to a short beep like thing insterd of alarm?

**Comment by hg8** [comment]
It does work.
Just give a try by yourself in your terminal : 

    paplay /usr/share/sounds/ubuntu/ringtones/Alarm\ clock.ogg

To get other sounds just check the list available in Ubuntu : 

```
$ ls -l /usr/share/sounds/ubuntu/ringtones/
total 520
-rw-r--r-- 1 root root 73696 Jun  5 19:21 alarm-clock-elapsed.oga
-rw-r--r-- 1 root root  5596 Jun  5 19:21 audio-volume-change.oga
-rw-r--r-- 1 root root  8495 Jun  5 19:21 bell.oga
-rw-r--r-- 1 root root 23142 Jun  5 19:21 camera-shutter.oga
-rw-r--r-- 1 root root 21073 Jun  5 19:21 complete.oga
[...]
```


On other distributions sounds location may vary (`/usr/share/sounds/freedesktop/stereo` on Arch Linux for example.)
